# Generated by Django 5.2.3 on 2025-06-25 08:28

import inventory.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_add_unique_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="reference_number",
            field=models.CharField(
                default=inventory.utils.generate_reference_number,
                help_text="A unique reference number for this movement",
                max_length=50,
                unique=True,
                verbose_name="Reference Number",
            ),
        ),
    ]
