# Generated by Django 5.2.3 on 2025-06-25 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_alter_stockmovement_reference_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockmovementitem",
            name="from_stockard",
        ),
        migrations.RemoveField(
            model_name="stockmovementitem",
            name="to_stockard",
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="warehouse",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_movements",
                to="inventory.warehouse",
                verbose_name="Warehouse",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stockmovementitem",
            name="from_stockard_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="From Stockard Name"
            ),
        ),
        migrations.AddField(
            model_name="stockmovementitem",
            name="to_stockard_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="To Stockard Name"
            ),
        ),
    ]
