# Generated by Django 5.2.3 on 2025-06-25 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_remove_stockmovementitem_from_stockard_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockmovementitem",
            name="from_stockard_name",
        ),
        migrations.RemoveField(
            model_name="stockmovementitem",
            name="to_stockard_name",
        ),
        migrations.AddField(
            model_name="stockmovementitem",
            name="from_stockard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outbound_movement_items",
                to="inventory.stockard",
                verbose_name="From Stockard",
            ),
        ),
        migrations.AddField(
            model_name="stockmovementitem",
            name="to_stockard",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inbound_movement_items",
                to="inventory.stockard",
                verbose_name="To Stockard",
            ),
        ),
    ]
