# Generated by Django 5.2.3 on 2025-06-25 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0006_remove_stockmovementitem_from_stockard_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockmovement",
            name="warehouse",
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="from_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outbound_movements",
                to="inventory.warehouse",
                verbose_name="From Warehouse",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="to_warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inbound_movements",
                to="inventory.warehouse",
                verbose_name="To Warehouse",
            ),
        ),
    ]
